name: Terraform Deployment

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment (dev, qa, prod)'
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      approve_apply:
        description: 'Approve Terraform Apply'
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  terraform-setup:
    name: Terraform Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init 
        working-directory: environments/${{github.event.inputs.environment}}
         
      - name: Terraform validate
        run: terraform validate
        working-directory: environments/${{github.event.inputs.environment}}

      - name: Terraform Plan
        run: terraform plan
        working-directory: environments/${{github.event.inputs.environment}}

      - name: Terraform Apply
        #if: github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: environments/${{github.event.inputs.environment}}
        
